# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "30c5af756ea767c28f82092b98ffc9e1"
name = "conversionai"
application_url = "https://conversionai-web-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_customers,read_orders,read_products,read_themes"

[auth]
redirect_urls = [
  "https://conversionai-web-production.up.railway.app/auth/callback",
  "https://conversionai-web-production.up.railway.app/auth/shopify/callback",
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/auth/shopify/callback"
]

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app-uninstalled"

[webhooks.privacy_compliance]
customer_deletion_url = "/webhooks/customers/redact"
customer_data_request_url = "/webhooks/customers/data-request"
shop_deletion_url = "/webhooks/shop/redact"
